### PR TITLE
Add logo

### LINKED ISSUE #38: Call for logo suggestions
Maybe do a competition by submitting a logo as comment here.

### PR DESCRIPTION
**Pull request by mosabua**
And alternative logos that were not the winners in the logo competition held as part of Trino Summit 2023

Fixes #38

### CODE REVIEW

**Review by Chaho12 — APPROVED** [review]
LGTM 👍

**Review by vishalya — APPROVED** [review]
LGTM

**Review by willmostly — COMMENTED** [review]
LGTM

**Review by raunaqmorarka — APPROVED** [review]

**Comment by mosabua** [comment]
Thank you @raunaqmorarka

**Review by martint — APPROVED** [review]

**Pull request merged**
