### PR TITLE
remove testng and used junit5 for trino-gateway project

### PR DESCRIPTION
**Pull request by andythsu**

### CODE REVIEW

**Comment by andythsu** [comment]
It looks like the tests keep failing on 
```
[ERROR] Failures: 
[ERROR]   TestRoutingGroupSelector.testByRoutingRulesEngineFileChange:125 expected: <etl2> but was: <etl>
```
Does anyone have any ideas?

**Comment by mosabua** [comment]
@andythsu this seems to be the same test that @willmostly and myself found to be flaky recently. Not sure at this stage but currently the main branch is green. Does it work locally?

**Comment by andythsu** [comment]
@mosabua it's super flaky. Local works like 50% of the time

**Review by mosabua — APPROVED** [review]
Looks great. Worked for me locally as well. Lets get this in and see how we can get the test to be less flaky in separate work later. 

That way we finished the removal of testng cleanly at least and dont have the temptation to add a testng based test accidentally.

Heads up @vishalya @willmostly @Chaho12 about the flaky test.

**Comment by mosabua** [comment]
In the future please make sure you follow the commit message guidelines for the Trino project - https://cbea.ms/git-commit/ .. also see https://github.com/trinodb/trino/blob/master/.github/DEVELOPMENT.md

**Pull request merged**
