### PR TITLE
Use and require Java 23

### PR DESCRIPTION
**Pull request by oneonestar**
## Description
Use and require Java 23.

## Release notes
(x) Release notes are required, with the following suggested text:

```markdown
* Require Java 23 for build and runtime.
```

### CODE REVIEW

**Comment by willmostly** [comment]
@oneonestar is this ready to review?

**Comment by mosabua** [comment]
I think this might also need an upgrade of airlift and airbase -- please check with @wendigo

**Comment by mosabua** [comment]
Also .. we probably want a separate PR in parallel that runs with 24-ea similar to how we run it in Trino

**Comment by oneonestar** [comment]
> is this ready to review?

@willmostly Yea.

> I think this might also need an upgrade of airlift and airbase -- please check with @wendigo

Sure #529

Since Java 22 is already EOL, we should roll this out soon.

**Review by willmostly — APPROVED** [review]
LGTM

**Comment by oneonestar** [comment]
Let's ship it together with Trino. 🚀
https://github.com/trinodb/trino/pull/23783

**Pull request merged**
