### PR TITLE
Add JmxOpenMetricsModule

### PR DESCRIPTION
**Pull request by oneonestar**
## Description
Add JmxOpenMetricsModule.

## Release notes
(x) Release notes are required, with the following suggested text:

```markdown
* Add openmetrics endpoint at `/metrics`
```

### CODE REVIEW

**Comment by mosabua** [comment]
Can you chime in here @mattstep ? Do we want to be able to enable/disable it or is this all built into the module and ready to go and we just got to update the docs?

**Comment by oneonestar** [comment]
OpenMetrics is different from OpenTelemetry.
Airlift module for OpenTelemetry is `io.airlift:tracing`.

**Review by willmostly — APPROVED** [review]
Looks good. Should we add the configuration snippet example [here](https://github.com/airlift/airlift/blob/6cd313e0a5472b0ca5ff770ddaefca02a669282d/openmetrics/README.md)?

**Comment by mosabua** [comment]
> OpenMetrics is different from OpenTelemetry. Airlift module for OpenTelemetry is `io.airlift:tracing`.

Ooops.

**Review by mosabua — APPROVED** [review]
Ship it.

**Pull request merged**
