### PR TITLE
Documentation update 

### PR DESCRIPTION
**Pull request by ruschecker**
This config required to let trino know that request has been proxied from gateway.

### CODE REVIEW

**Review by Chaho12 — COMMENTED** [review]
idk this will be necessary as it will be added by default.
@vishalya what do you think?

- https://github.com/trinodb/trino-gateway/pull/194

**Comment by mosabua** [comment]
The Trino Gateway configuration is separate from the Trino configuration.. we might need both. This PR would have to move the changes into a section that talks about the Trino cluster configuration.

And @vishalya is still updating his PR to add the same config to the docker example config and then we will merge that PR separately.

**Comment by mosabua** [comment]
👋 @ruschecker .. are you going to update this PR or should I send a replacement addressing the concerns raised in the review.

**Comment by mosabua** [comment]
Replaced by #297

**Pull request closed without merging**
