### PR TITLE
Fix pnpm-lock.yaml having hardcoded dependency path in version

### PR DESCRIPTION
**Pull request by andythsu**
## Description

Get rid of the hardcoded dependency path in `pnpm-lock.yaml` to allow download from other URLs. This is a follow-up of https://github.com/trinodb/trino-gateway/pull/303

## Release notes

(X) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
* 
```

### CODE REVIEW

**Comment by ytwp** [comment]
Looks great👍

**Comment by oneonestar** [comment]
I'm not sure how to review this kind of changes.
Can we reproduce the same output using some command?

**Comment by andythsu** [comment]
I'm assuming everyone would come up with somewhat different minor/patch versions since it depends on the version. I think these changes are one-time only and as long as the majority of reviewers can also build it using this updated `pnpm-lock`, we should be fine

**Comment by mosabua** [comment]
Isnt the lock file required to ensure that the build is repeatable and the same no matter where you build it .. at least thats how lock files work in rubygems and other tools.. so I think we should NOT remove the file

**Comment by andythsu** [comment]
You are correct about the intent of the lock file, but I'm NOT removing the file.

Instead, I'm removing the hardcoded path.

It looks like this now:
```
dependencies:
  '@douyinfe/semi-icons':
    specifier: ^2.47.1
    version: registry.npmmirror.com/@douyinfe/semi-icons@2.47.1(react@18.2.0)
```

The `registry.npmmirror.com` specifies the download path, which is unnecessary

With current PR and https://github.com/trinodb/trino-gateway/pull/303, we can just use 

```
dependencies:
  '@douyinfe/semi-icons':
    specifier: ^2.47.1
    version: 2.47.1(react@18.2.0)
```

**Comment by mosabua** [comment]
Oh .. I get it. Is markup supported by pnpm .. if yes.. I am good with the change

**Comment by andythsu** [comment]
what do you mean by is markup supported by pnpm?

the pnpm registry url is defined in the pom file, which shouldn't be touched that often unless we add more dependencies. 

how do we ensure they don't sneak back in... i'm not sure.. maybe we just need to be more careful if we see a pnpm-lock change?

**Comment by andythsu** [comment]
not sure if there's such tool to validate the integrity of the lock file 🤔

**Comment by andythsu** [comment]
@ytwp do you know any?

**Comment by mosabua** [comment]
Well... is it complaining about errors with the modified file or does it just work .. if it works.. we are good. I have not had a chance to test....

**Comment by andythsu** [comment]
nope. There's no complaints for me with the modified file. It works as expected.

**Review by mosabua — APPROVED** [review]
Lets ship it!

**Comment by ytwp** [comment]
If `registry.npmmirror.com` is specified, it will be downloaded from there. If not specified, it will be downloaded from `pnpm config get registry`.

**Pull request merged**
