### PR TITLE
Improve navigation for docs

### PR DESCRIPTION
**Pull request by mosabua**
- Add logo on each page
- Use same layout in readme
- Use only three columns but add item lists

Please review @willmostly @vishalya @Chaho12

### CODE REVIEW

**Review by Chaho12 — APPROVED** [review]
I guess no more bolding current page link?
 
LGTM 👍

**Comment by mosabua** [comment]
> I guess no more bolding current page link?

No .. ultimately I think we need to get a little website that deploys to github pages via a different branch going. I know how to do all that .. just need to figure out how this relates to plans I have with the Trino docs themselves..

**Review by willmostly — APPROVED** [review]
LGTM. It will be nice once Sphinx is introduced so we don't have to change each doc page manually.

**Review by ebyhr — APPROVED** [review]

**Comment by mosabua** [comment]
Thank you @ebyhr @willmostly and @Chaho12

**Pull request merged**
