### PR TITLE
Update Trino dependencies to 464

### PR DESCRIPTION
**Pull request by Chaho12**
## Description

Trino 464 requiring Java 23 is merged yesterday, but not released yet. 
We can merge PR when they release it.

## Additional context and related issues

https://github.com/trinodb/trino-gateway/pull/486
https://github.com/trinodb/trino/pull/23783

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
( ) Release notes are required, with the following suggested text:

```markdown
* Fix some things. ({issue}`issuenumber`)
```

### CODE REVIEW

**Comment by ebyhr** [comment]
Trino released 463 (not 464) yesterday.

**Comment by ebyhr** [comment]
Please reopen after Trino released 464.

**Comment by mosabua** [comment]
I am just reopening and setting it to draft so others are aware of this effort.

**Comment by mosabua** [comment]
Please also upgrade in the TrinoGatewayRunner class and see what we have in use in the quickstart and other docs.

**Comment by mosabua** [comment]
Any concerns with reopening @ebyhr ?

**Comment by ebyhr** [comment]
There is no benefit to keep opening a PR which cannot build.

**Comment by mosabua** [comment]
> There is no benefit to keep opening a PR which cannot build.

The benefit is that others can see that it exists and dont try to do the same work .. I nearly did exactly that. And a build failure is no big deal in this case in my opinion.

**Comment by ebyhr** [comment]
What is the motivation sending a PR which upgrades to the version which doesn't exist?

**Comment by mosabua** [comment]
Opening now to see how CI goes.

**Review by mosabua — APPROVED** [review]
Looks good ..

**Pull request merged**
