### PR TITLE
Use JDBI for ResourceGroups and Remove activejdbc

### LINKED ISSUE #229: Replace ActiveJDBC with JDBI
The example PR is https://github.com/trinodb/trino-gateway/pull/145

- [x] query_history #145
- [ ] selectors https://github.com/trinodb/trino-gateway/pull/284
- [x] exact_match_source_selectors https://github.com/trinodb/trino-gateway/pull/285
- [x] gateway_backend #231
- [ ] resource_groups
- [x] resource_groups_global_properties #230

### PR DESCRIPTION
**Pull request by oneonestar**
## Description
Close #229. Depends on #284.
* Use JDBI for ResourceGroups
* Remove activejdbc completely

The cache provided by activejdbc for ResourceGroups will be gone with this PR.
We might need to implement a cache if performance degradation is significant.

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

**Review by mosabua — APPROVED** [review]
I think this is a good replacement for ActiveJDBC with JDBI. We should merge it after the conflict is resolved and the required other JDBI refactor is merged. Any concerns @ebyhr ?

**Comment by oneonestar** [comment]
Rebase done.

**Comment by mosabua** [comment]
One more rebase .. then I can merge.

**Comment by oneonestar** [comment]
Done

**Pull request merged**
