### PR TITLE
Upgrade UI

### PR DESCRIPTION
**Pull request by mosabua**
## Description

- Node from v18.9.1 to latest LTS version v20.17.0
- pnpm from 8.6.12 to latest version 9.11.0
- Including all transitive dependencies

## Release notes

(x) No release notes entry needed.

### CODE REVIEW

**Review by ytwp — APPROVED** [review]

**Comment by mosabua** [comment]
Did you do any further testing on this @ytwp  .. cause I did not..

**Review by ebyhr — APPROVED** [review]

**Comment by ebyhr** [comment]
> (x) Release notes are required, with the following suggested text:

Why do we need to mention this change in release notes?

**Comment by ytwp** [comment]
> Did you do any further testing on this @ytwp .. cause I did not..

I have tested it, and Node v20.17.0 works well.

**Comment by mosabua** [comment]
> > (x) Release notes are required, with the following suggested text:
> 
> Why do we need to mention this change in release notes?

I was thinking it might introduce some incompatibility with extensions or so but I think we are all good.

**Pull request merged**
